// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmaQMS.API.Data;

#nullable disable

namespace PharmaQMS.API.Migrations.Domain
{
    [DbContext(typeof(DomainDbContext))]
    partial class DomainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PharmaQMS.API.Models.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Actie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("EntiteitId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EntiteitType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("GebruikerId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("IPAdres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NieuweWaarde")
                        .HasColumnType("longtext");

                    b.Property<string>("OudWaarde")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Tijdstip")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EntiteitType");

                    b.HasIndex("GebruikerId");

                    b.HasIndex("Tijdstip");

                    b.HasIndex("EntiteitType", "EntiteitId");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("PharmaQMS.API.Models.Entities.Bmr", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("BatchSize")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<Guid>("MasterRecipeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("MasterRecipeId1")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductionLineId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ProductionLineId1")
                        .HasColumnType("char(36)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("BatchNumber");

                    b.HasIndex("CreatedById");

                    b.HasIndex("MasterRecipeId");

                    b.HasIndex("MasterRecipeId1");

                    b.HasIndex("ProductionLineId");

                    b.HasIndex("ProductionLineId1");

                    b.ToTable("Bmrs", (string)null);
                });

            modelBuilder.Entity("PharmaQMS.API.Models.Entities.BmrLotLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BmrId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BmrId1")
                        .HasColumnType("char(36)");

                    b.Property<int>("LotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BmrId");

                    b.HasIndex("BmrId1");

                    b.HasIndex("LotId");

                    b.HasIndex("BmrId", "LotId")
                        .IsUnique();

                    b.ToTable("BmrLotLinks", (string)null);
                });

            modelBuilder.Entity("PharmaQMS.API.Models.Entities.BmrStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BmrId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DeviationNote")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("EnteredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EnteredById")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("EnteredData")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("MasterRecipeStepId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("MasterRecipeStepId1")
                        .HasColumnType("char(36)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VerifiedById")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BmrId");

                    b.HasIndex("EnteredById");

                    b.HasIndex("MasterRecipeStepId");

                    b.HasIndex("MasterRecipeStepId1");

                    b.HasIndex("VerifiedById");

                    b.ToTable("BmrSteps", (string)null);
                });

            modelBuilder.Entity("PharmaQMS.API.Models.Entities.Lot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnalysisCertificate")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ExpiryDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PurchaseOrderNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("RawMaterialId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceivedDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("RawMaterialId");

                    b.HasIndex("ReceivedDateUtc");

                    b.HasIndex("Status");

                    b.HasIndex("RawMaterialId", "LotNumber")
                        .IsUnique();

                    b.ToTable("Lots", (string)null);
                });

            modelBuilder.Entity("PharmaQMS.API.Models.Entities.MasterRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeName");

                    b.ToTable("MasterRecipes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000001"),
                            IsApproved = true,
                            RecipeName = "AMOX-500MG-CAP",
                            Version = "3.1"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000002"),
                            IsApproved = true,
                            RecipeName = "AMOX-250MG-CAP",
                            Version = "2.0"
                        });
                });

            modelBuilder.Entity("PharmaQMS.API.Models.Entities.MasterRecipeStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ExpectedFields")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("MasterRecipeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MasterRecipeId");

                    b.HasIndex("MasterRecipeId", "StepNumber")
                        .IsUnique();

                    b.ToTable("MasterRecipeSteps", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000001"),
                            ExpectedFields = "Gewicht (kg)",
                            IsCritical = true,
                            MasterRecipeId = new Guid("22222222-0000-0000-0000-000000000001"),
                            StepName = "Grondstoffen wegen",
                            StepNumber = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000002"),
                            ExpectedFields = "Mengtijd (min)",
                            IsCritical = false,
                            MasterRecipeId = new Guid("22222222-0000-0000-0000-000000000001"),
                            StepName = "Mengen",
                            StepNumber = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000003"),
                            ExpectedFields = "Temperatuur (°C); Tijd (min)",
                            IsCritical = true,
                            MasterRecipeId = new Guid("22222222-0000-0000-0000-000000000001"),
                            StepName = "Granuleren",
                            StepNumber = 3
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000004"),
                            ExpectedFields = "Vochtigheid (%)",
                            IsCritical = false,
                            MasterRecipeId = new Guid("22222222-0000-0000-0000-000000000001"),
                            StepName = "Drogen",
                            StepNumber = 4
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000005"),
                            ExpectedFields = "Vulgewicht (mg)",
                            IsCritical = true,
                            MasterRecipeId = new Guid("22222222-0000-0000-0000-000000000001"),
                            StepName = "Capsules vullen",
                            StepNumber = 5
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000006"),
                            ExpectedFields = "Resultaat",
                            IsCritical = true,
                            MasterRecipeId = new Guid("22222222-0000-0000-0000-000000000001"),
                            StepName = "In-process kwaliteitscheck",
                            StepNumber = 6
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000007"),
                            ExpectedFields = "Gewicht (kg)",
                            IsCritical = true,
                            MasterRecipeId = new Guid("22222222-0000-0000-0000-000000000002"),
                            StepName = "Grondstoffen wegen",
                            StepNumber = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000008"),
                            ExpectedFields = "Mengtijd (min)",
                            IsCritical = false,
                            MasterRecipeId = new Guid("22222222-0000-0000-0000-000000000002"),
                            StepName = "Mengen",
                            StepNumber = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000009"),
                            ExpectedFields = "Vulgewicht (mg)",
                            IsCritical = true,
                            MasterRecipeId = new Guid("22222222-0000-0000-0000-000000000002"),
                            StepName = "Capsules vullen",
                            StepNumber = 3
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000010"),
                            ExpectedFields = "Resultaat",
                            IsCritical = true,
                            MasterRecipeId = new Guid("22222222-0000-0000-0000-000000000002"),
                            StepName = "In-process kwaliteitscheck",
                            StepNumber = 4
                        });
                });

            modelBuilder.Entity("PharmaQMS.API.Models.Entities.ProductionLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("LineName");

                    b.ToTable("ProductionLines", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            IsActive = true,
                            LineName = "Lijn A",
                            Location = "Hal 1"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            IsActive = true,
                            LineName = "Lijn B",
                            Location = "Hal 1"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            IsActive = true,
                            LineName = "Lijn C",
                            Location = "Hal 2"
                        });
                });

            modelBuilder.Entity("PharmaQMS.API.Models.Entities.QcTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("TestObjectId")
                        .HasColumnType("int");

                    b.Property<string>("TestObjectType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("QcTests", (string)null);
                });

            modelBuilder.Entity("PharmaQMS.API.Models.Entities.QcTestParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Max")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MeasuredValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Min")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("QcTestId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("QcTestId");

                    b.ToTable("QcTestParameters", (string)null);
                });

            modelBuilder.Entity("PharmaQMS.API.Models.Entities.RawMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Category")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("CepNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("MaxSpecificationLimit")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("MinSpecificationLimit")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("PharmaceuticalApi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CepNumber");

                    b.HasIndex("Name");

                    b.HasIndex("PharmaceuticalApi");

                    b.ToTable("RawMaterials", (string)null);
                });

            modelBuilder.Entity("PharmaQMS.API.Models.Entities.Bmr", b =>
                {
                    b.HasOne("PharmaQMS.API.Models.Entities.MasterRecipe", "MasterRecipe")
                        .WithMany()
                        .HasForeignKey("MasterRecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaQMS.API.Models.Entities.MasterRecipe", null)
                        .WithMany("Bmrs")
                        .HasForeignKey("MasterRecipeId1");

                    b.HasOne("PharmaQMS.API.Models.Entities.ProductionLine", "ProductionLine")
                        .WithMany()
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaQMS.API.Models.Entities.ProductionLine", null)
                        .WithMany("Bmrs")
                        .HasForeignKey("ProductionLineId1");

                    b.Navigation("MasterRecipe");

                    b.Navigation("ProductionLine");
                });

            modelBuilder.Entity("PharmaQMS.API.Models.Entities.BmrLotLink", b =>
                {
                    b.HasOne("PharmaQMS.API.Models.Entities.Bmr", "Bmr")
                        .WithMany()
                        .HasForeignKey("BmrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaQMS.API.Models.Entities.Bmr", null)
                        .WithMany("LotLinks")
                        .HasForeignKey("BmrId1");

                    b.HasOne("PharmaQMS.API.Models.Entities.Lot", "Lot")
                        .WithMany()
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bmr");

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("PharmaQMS.API.Models.Entities.BmrStep", b =>
                {
                    b.HasOne("PharmaQMS.API.Models.Entities.Bmr", "Bmr")
                        .WithMany("Steps")
                        .HasForeignKey("BmrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaQMS.API.Models.Entities.MasterRecipeStep", "MasterRecipeStep")
                        .WithMany()
                        .HasForeignKey("MasterRecipeStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaQMS.API.Models.Entities.MasterRecipeStep", null)
                        .WithMany("BmrSteps")
                        .HasForeignKey("MasterRecipeStepId1");

                    b.Navigation("Bmr");

                    b.Navigation("MasterRecipeStep");
                });

            modelBuilder.Entity("PharmaQMS.API.Models.Entities.Lot", b =>
                {
                    b.HasOne("PharmaQMS.API.Models.Entities.RawMaterial", "RawMaterial")
                        .WithMany("Lots")
                        .HasForeignKey("RawMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RawMaterial");
                });

            modelBuilder.Entity("PharmaQMS.API.Models.Entities.MasterRecipeStep", b =>
                {
                    b.HasOne("PharmaQMS.API.Models.Entities.MasterRecipe", "MasterRecipe")
                        .WithMany("Steps")
                        .HasForeignKey("MasterRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterRecipe");
                });

            modelBuilder.Entity("PharmaQMS.API.Models.Entities.QcTestParameter", b =>
                {
                    b.HasOne("PharmaQMS.API.Models.Entities.QcTest", "QcTest")
                        .WithMany("Parameters")
                        .HasForeignKey("QcTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QcTest");
                });

            modelBuilder.Entity("PharmaQMS.API.Models.Entities.Bmr", b =>
                {
                    b.Navigation("LotLinks");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("PharmaQMS.API.Models.Entities.MasterRecipe", b =>
                {
                    b.Navigation("Bmrs");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("PharmaQMS.API.Models.Entities.MasterRecipeStep", b =>
                {
                    b.Navigation("BmrSteps");
                });

            modelBuilder.Entity("PharmaQMS.API.Models.Entities.ProductionLine", b =>
                {
                    b.Navigation("Bmrs");
                });

            modelBuilder.Entity("PharmaQMS.API.Models.Entities.QcTest", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("PharmaQMS.API.Models.Entities.RawMaterial", b =>
                {
                    b.Navigation("Lots");
                });
#pragma warning restore 612, 618
        }
    }
}
